from .config import (
    ADD_BLANK as ADD_BLANK,
    FILTER_LENGTH as FILTER_LENGTH,
    HOP_LENGTH as HOP_LENGTH,
    MODEL_PARAMS as MODEL_PARAMS,
    N_SPEAKERS as N_SPEAKERS,
    NUM_LANGUAGES as NUM_LANGUAGES,
    NUM_TONES as NUM_TONES,
    SAMPLING_RATE as SAMPLING_RATE,
    SEGMENT_FRAMES as SEGMENT_FRAMES,
    SPEC_CHANNELS as SPEC_CHANNELS,
    SPK2ID as SPK2ID,
)
