/**
 * German grapheme-to-phoneme. 1:1 port of dittli_tts/text/german.py.
 *
 * Rules and exceptions are loaded from g2p_de_rules.json (generated by
 * scripts/gen_de_rules.py) — never edit them here, edit the Python source
 * and regenerate.
 */

import _RULES_DATA from "./g2p_de_rules.json" with { type: "json" };

const EXCEPTIONS = _RULES_DATA.exceptions;
const RULES = _RULES_DATA.rules;
const PREFIXES = _RULES_DATA.prefixes;
const LOANWORD_V_FRAGMENTS = _RULES_DATA.loanword_v_fragments;
const ABBREVIATIONS = _RULES_DATA.abbreviations;
const BACK_VOWELS = _RULES_DATA.back_vowels;
const ALL_VOWELS = _RULES_DATA.all_vowels;
const WORD_CHARS = new Set(_RULES_DATA.word_chars.split(""));

// ---------------------------------------------------------------------------
// Context-sensitive callbacks. Must match german.py exactly.
// ---------------------------------------------------------------------------

function chRule(word, i) {
  if (i === 0) return ["k"];
  if (i >= 2 && word.slice(i - 2, i) === "au") return ["x"];
  const prev = word[i - 1];
  if (BACK_VOWELS.includes(prev)) return ["x"];
  return ["ç"];
}

function chsRule(word, i) {
  if (i + 3 === word.length || (i + 3 < word.length && word[i + 3] === "t")) {
    return ["k", "s"];
  }
  return chRule(word, i).concat(["s"]);
}

function stRule(word, i) {
  if (i === 0) return ["ʃ", "t"];
  for (const p of PREFIXES) {
    if (word.startsWith(p) && i === p.length) return ["ʃ", "t"];
  }
  return ["s", "t"];
}

function spRule(word, i) {
  if (i === 0) return ["ʃ", "p"];
  for (const p of PREFIXES) {
    if (word.startsWith(p) && i === p.length) return ["ʃ", "p"];
  }
  return ["s", "p"];
}

function rRule(word, i) {
  if (i === word.length - 1 && i > 0 && ALL_VOWELS.includes(word[i - 1])) {
    return ["ɐ"];
  }
  if (word.endsWith("er") && i === word.length - 1) return ["ɐ"];
  return ["ʁ"];
}

function sRule(word, i) {
  if (i === 0 && i + 1 < word.length && ALL_VOWELS.includes(word[i + 1])) {
    return ["z"];
  }
  if (
    i > 0 &&
    i < word.length - 1 &&
    ALL_VOWELS.includes(word[i - 1]) &&
    ALL_VOWELS.includes(word[i + 1])
  ) {
    return ["z"];
  }
  return ["s"];
}

function vRule(word, _i) {
  for (const frag of LOANWORD_V_FRAGMENTS) {
    if (word.includes(frag)) return ["v"];
  }
  return ["f"];
}

const CALLBACKS = {
  ch: chRule,
  chs: chsRule,
  st: stRule,
  sp: spRule,
  r: rRule,
  s: sRule,
  v: vRule,
};

// ---------------------------------------------------------------------------
// Number normalization (port of dittli_tts/text/german_utils/number_norm.py).
// ---------------------------------------------------------------------------

const _ONES = ["null", "eins", "zwei", "drei", "vier", "fünf", "sechs", "sieben", "acht", "neun"];
const _TEENS = {
  10: "zehn",
  11: "elf",
  12: "zwölf",
  13: "dreizehn",
  14: "vierzehn",
  15: "fünfzehn",
  16: "sechzehn",
  17: "siebzehn",
  18: "achtzehn",
  19: "neunzehn",
};
const _TENS = {
  20: "zwanzig",
  30: "dreißig",
  40: "vierzig",
  50: "fünfzig",
  60: "sechzig",
  70: "siebzig",
  80: "achtzig",
  90: "neunzig",
};

function _underHundred(n) {
  if (n < 10) return _ONES[n];
  if (_TEENS[n] !== undefined) return _TEENS[n];
  const tens = Math.floor(n / 10) * 10;
  const ones = n % 10;
  if (ones === 0) return _TENS[tens];
  const onesWord = ones === 1 ? "ein" : _ONES[ones];
  return `${onesWord}und${_TENS[tens]}`;
}

function _underThousand(n) {
  if (n < 100) return _underHundred(n);
  const hundreds = Math.floor(n / 100);
  const rest = n % 100;
  const head = hundreds === 1 ? "ein" : _ONES[hundreds];
  return rest === 0 ? `${head}hundert` : `${head}hundert${_underHundred(rest)}`;
}

function _underMillion(n) {
  if (n < 1000) return _underThousand(n);
  const thousands = Math.floor(n / 1000);
  const rest = n % 1000;
  const head = thousands === 1 ? "ein" : _underThousand(thousands);
  return rest === 0 ? `${head}tausend` : `${head}tausend${_underThousand(rest)}`;
}

export function numberToWords(n) {
  if (n < 0) return `minus ${numberToWords(-n)}`;
  if (n < 1_000_000) return _underMillion(n);
  if (n < 1_000_000_000) {
    const millions = Math.floor(n / 1_000_000);
    const rest = n % 1_000_000;
    const m = millions === 1 ? "eine Million" : `${_underMillion(millions)} Millionen`;
    return rest === 0 ? m : `${m} ${_underMillion(rest)}`;
  }
  const billions = Math.floor(n / 1_000_000_000);
  const rest = n % 1_000_000_000;
  const b = billions === 1 ? "eine Milliarde" : `${_underMillion(billions)} Milliarden`;
  return rest === 0 ? b : `${b} ${_underMillion(rest)}`;
}

export function normalizeNumbers(text) {
  return text.replace(/-?\d+/g, (m) => numberToWords(parseInt(m, 10)));
}

export function expandAbbreviations(text) {
  for (const [pattern, expansion] of ABBREVIATIONS) {
    text = text.replace(new RegExp(pattern, "g"), expansion);
  }
  return text;
}

export function normalizeText(text) {
  return normalizeNumbers(expandAbbreviations(text));
}

// ---------------------------------------------------------------------------
// Rule scanner.
// ---------------------------------------------------------------------------

export function _applyRules(word) {
  word = word.toLowerCase();
  const out = [];
  let i = 0;
  const n = word.length;
  while (i < n) {
    let matched = false;
    for (const [pattern, action] of RULES) {
      const plen = pattern.length;
      if (i + plen <= n && word.slice(i, i + plen) === pattern) {
        if (typeof action === "object" && !Array.isArray(action) && action.callback) {
          out.push(...CALLBACKS[action.callback](word, i));
        } else {
          out.push(...action);
        }
        i += plen;
        matched = true;
        break;
      }
    }
    if (!matched) {
      i += 1;
    }
  }
  return out;
}

function _mapPhoneme(ph, symbolSet) {
  const rep = { "\n": ".", "...": "…", v: "V" };
  if (rep[ph] !== undefined) ph = rep[ph];
  if (symbolSet && !symbolSet.has(ph)) return "UNK";
  return ph;
}

function _splitPunct(token) {
  const lower = token.toLowerCase();
  const n = lower.length;
  let a = 0;
  while (a < n && !WORD_CHARS.has(lower[a])) a += 1;
  let b = n;
  while (b > a && !WORD_CHARS.has(lower[b - 1])) b -= 1;
  return [token.slice(0, a), token.slice(a, b), token.slice(b)];
}

/**
 * Public API: graphemeToPhonemeDE(text, opts) -> { phones, tones, word2ph }
 *
 * `opts.symbolSet` (Set<string>) — if provided, phonemes not in it are mapped
 *   to "UNK". Pass the `symbols` array from the model metadata sidecar.
 * `opts.padStartEnd` (boolean, default true) — match Python pad_start_end.
 */
export function graphemeToPhonemeDE(text, opts = {}) {
  const { symbolSet = null, padStartEnd = true } = opts;
  text = normalizeText(text);
  const rawWords = text.split(/\s+/).filter((w) => w.length > 0);
  const phones = [];
  const tones = [];
  const word2ph = [];

  for (const raw of rawWords) {
    const [lead, core, trail] = _splitPunct(raw);

    for (const ch of lead) {
      phones.push(_mapPhoneme(ch, symbolSet));
      tones.push(0);
      word2ph.push(1);
    }

    if (core) {
      const lower = core.toLowerCase();
      let phList = EXCEPTIONS[lower] ? EXCEPTIONS[lower].slice() : _applyRules(lower);
      phList = phList.map((p) => _mapPhoneme(p, symbolSet));
      phones.push(...phList);
      for (let i = 0; i < phList.length; i++) tones.push(0);
      word2ph.push(phList.length);
    }

    for (const ch of trail) {
      phones.push(_mapPhoneme(ch, symbolSet));
      tones.push(0);
      word2ph.push(1);
    }
  }

  if (padStartEnd) {
    phones.unshift("_");
    phones.push("_");
    tones.unshift(0);
    tones.push(0);
    word2ph.unshift(1);
    word2ph.push(1);
  }
  return { phones, tones, word2ph };
}
